name: compound
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  drift: ^2.30.1
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.5
  drift_dev: ^2.30.1

flutter:
  uses-material-design: true

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/font/LeagueSpartan-VF.ttf
